{
	"version": 1607320922,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tilemap.png",
		"images/tilemap2.png",
		"images/waterfountain-sheet0.png",
		"images/vendingmachine-sheet0.png",
		"images/streetlightoff-sheet0.png",
		"images/pinetree-sheet0.png",
		"images/apartmentbuilding-sheet0.png",
		"images/grocerystore-sheet0.png",
		"images/oldcoffeeshop-sheet0.png",
		"images/tree-sheet0.png",
		"images/flowerpot-sheet0.png",
		"images/mailbox-sheet0.png",
		"images/trashcan-sheet0.png",
		"images/parkbench-sheet0.png",
		"images/oldtreestump-sheet0.png",
		"images/deadtree-sheet0.png",
		"images/deadtree2-sheet0.png",
		"images/weepingwillowtree-sheet0.png",
		"images/house-sheet0.png",
		"images/house2-sheet0.png",
		"images/police-sheet0.png",
		"images/police-sheet1.png",
		"images/tiledbackground.png",
		"images/gamepad-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/gamepad_middle-sheet0.png",
		"images/bullets1-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/spawn-sheet0.png",
		"images/tilemap3.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/logos2-sheet0.png",
		"images/pause-sheet0.png",
		"images/pause-sheet1.png",
		"images/mute-sheet0.png",
		"images/pausedlogo-sheet0.png",
		"images/mute2-sheet0.png",
		"images/back-sheet0.png",
		"images/play_button_-sheet0.png",
		"images/how_to_play_button-sheet0.png",
		"images/exit_button-sheet0.png",
		"images/gameover-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/health_bar-sheet0.png",
		"images/coronavirus_killed_bar-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/warning-sheet0.png",
		"images/right_sign-sheet0.png",
		"images/right_sign2-sheet0.png",
		"images/warning2-sheet0.png",
		"images/left_sign-sheet0.png",
		"images/npc1-sheet0.png",
		"images/npc1-sheet1.png",
		"images/npcmove.png",
		"images/npc2-sheet0.png",
		"images/npc2-sheet1.png",
		"images/npc3-sheet0.png",
		"images/npc3-sheet1.png",
		"images/npc4-sheet0.png",
		"images/npc4-sheet1.png",
		"images/spawnnpc-sheet0.png",
		"images/stayhome-sheet0.png",
		"images/saved_people-sheet0.png",
		"images/about_us_button-sheet0.png",
		"images/credit-sheet0.png",
		"images/hotople-sheet0.png",
		"images/space-sheet0.png",
		"images/arrow-sheet0.png",
		"images/spacechar-sheet0.png",
		"images/paus-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/loadddd-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/hotople2-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/spritefont.png",
		"images/baseanalog-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/up-sheet0.png",
		"images/bottom-sheet0.png",
		"images/up_right-sheet0.png",
		"images/right_bottom-sheet0.png",
		"media/game over.m4a",
		"media/select.m4a",
		"media/game over.ogg",
		"media/select.ogg",
		"media/spray.ogg",
		"media/die.ogg",
		"media/spray (mp3cut.net).m4a",
		"media/spray (mp3cut.net).ogg",
		"media/die_2.ogg",
		"media/game over (mp3cut.net).ogg",
		"media/game over sound effects (mp3cut.net).ogg",
		"media/kid sound effect child sound effect (mp3cut.net).ogg",
		"media/in game.m4a",
		"media/in-game.ogg",
		"media/opening.m4a",
		"media/opening_1.ogg",
		"media/in game (mp3cut.net).ogg",
		"media/opening_1 (mp3cut.net).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"generator_config.txt",
		"pixeboy-z8xgd-demo.html",
		"pixeboy-z8xgd-webfont.woff",
		"pixeboy-z8xgd-webfont.woff2",
		"stylesheet.css"
	]
}